# Part 1. Numpy for numerical computations

## 1.1 Introduction to Numpy
Numpy is a powerful library for numerical computations in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures.
The full official documentation for Numpy can be found [here](https://numpy.org/doc/stable/).



## 1.2 Numpy Objects: N-dimensional Arrays

Numpy uses objects called arrays. They are **similar to Python lists but offer more functionality and are more efficient for numerical operations**. They are also **significantly faster** to use in computations than Python lists. The speed-up is that numpy arrays only contain elements of the **same data type** (homogeneous data structures), as opposed to python lists which can contain multiple different data types (heterogeneous data structures).

Most NumPy arrays have some restrictions. For instance:
- All elements of the array must be of the same type of data.
- The shape must be “rectangular”, e.g., each row of a two-dimensional array must have the same number of columns.

We will use the word “array” to refer to an instance of ndarray.

Then, we can create and manipulate arrays of any dimension by using the `np.array()` function:

Syntax:
``arr = np.array(data, dtype)``


In [10]:
import numpy as np  

# Creating a 1D array from a list
arr1d = np.array([1, 2, 3, 4, 5], dtype=float)  
print("\nArray 1D:\n ", arr1d)    

# Creating a 2D array from a list of lists
arr2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)  
print("\nArray 2D:\n",arr2d)

# Creating a 2D array from a list of lists with a specified data type
arr2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)  
print("\nArray 2D:\n", arr2d)

# Creating a 3D array from a list of lists of lists
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=float)
print("\nArray 3D:\n", arr3d)


Array 1D:
  [1. 2. 3. 4. 5.]

Array 2D:
 [[1. 2. 3.]
 [4. 5. 6.]]

Array 2D:
 [[1. 2. 3.]
 [4. 5. 6.]]

Array 3D:
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


NumPy also supports 0-dimensional arrays, however they are not very useful.

In [2]:
# Creating a 0D array
arr0d = np.array(42)  
print(arr0d)
print(arr0d.ndim) 

42
0



**Short exercise**: Create a 1D array, a 2D array, and a 3D array with different data types. 1D array with integers, 2D array with floats, and 3D array with complex numbers.

```{admonition} Example here!
:class: dropdown
```python
import numpy as np

# Creating a 1D array with integers
arr1d = np.array([1, 2, 3, 4, 5], dtype=int)

# Creating a 2D array with floats
arr2d = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]], dtype=float)   

# Creating a 3D array with complex numbers
arr3d = np.array([[[1+2j, 3+4j], [5+6j, 7+8j]], [[9+10j, 11+12j], [13+14j, 15+16j]]], dtype=complex)  

```


In some cases it can be useful to create arrays with specific type of floating point numbers. Numpy supports several floating point types, each with different precision and memory requirements. The most commonly data types in Numpy are:

| Data Type | Description |
|-----------|-------------|
| int8     | 8-bit signed integer |
| int16    | 16-bit signed integer |
| int32    | 32-bit signed integer |
| int64    | 64-bit signed integer |
| float16  | Half precision float: sign bit, 5 bits exponent, 10 bits fraction |
| float32  | Single precision float: sign bit, 8 bits exponent, 23 bits fraction |
| float64  | Double precision float: sign bit, 11 bits exponent, 52 bits fraction |
| complex64 | Complex number, represented by two 32-bit floats (real and imaginary parts) |
| complex128 | Complex number, represented by two 64-bit floats (real and imaginary parts) |

In [4]:
# examples of arrays with different data types
arr_int = np.array([1, 2, 3], dtype=int)
arr_float = np.array([1.1, 2.2, 3.3], dtype=float)
arr_complex = np.array([1+2j, 3+4j, 5+6j], dtype=complex)

print(arr_int, arr_int.dtype)
print(arr_float, arr_float.dtype)
print(arr_complex, arr_complex.dtype)


[1 2 3] int64
[1.1 2.2 3.3] float64
[1.+2.j 3.+4.j 5.+6.j] complex128



### 1.2.1 Array Attributes

We can print out essential attributes of a Numpy array as follows:
- `ndarray.ndim`: Returns the number of dimensions (axes) of the array.
- `ndarray.shape`: Returns a tuple representing the dimensions of the array.
- `ndarray.size`: Returns the total number of elements in the array.
- `ndarray.dtype`: Returns the data type of the elements in the array.


In [12]:
import numpy as np
# Creating a 1D array from a list
arr1d = np.array([1, 2, 3, 4, 5], dtype=float)  
print("\nArray 1D:\n ", arr1d) 
print("Array 1D attributes:")
print("ndim:", arr1d.ndim)
print("shape:", arr1d.shape)
print("size:", arr1d.size)
print("dtype:", arr1d.dtype)

# Creating a 2D array from a list of lists
arr2d = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)  
print("\nArray 2D:\n",arr2d)
print("Array 2D attributes:")
print("ndim:", arr2d.ndim)
print("shape:", arr2d.shape)
print("size:", arr2d.size)
print("dtype:", arr2d.dtype)

# Creating a 3D array from a list of lists of lists
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=float)
print("\nArray 3D:\n", arr3d)
print("Array 3D attributes:")
print("ndim:", arr3d.ndim)
print("shape:", arr3d.shape)
print("size:", arr3d.size)
print("dtype:", arr3d.dtype)


Array 1D:
  [1. 2. 3. 4. 5.]
Array 1D attributes:
ndim: 1
shape: (5,)
size: 5
dtype: float64

Array 2D:
 [[1. 2. 3.]
 [4. 5. 6.]]
Array 2D attributes:
ndim: 2
shape: (2, 3)
size: 6
dtype: float64

Array 3D:
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
Array 3D attributes:
ndim: 3
shape: (2, 2, 2)
size: 8
dtype: float64


## 1.3 Non-numeric data types in Numpy
Despite being primarily designed for numerical data, Numpy also supports non-numeric data types, such as strings and booleans. Here are some examples of how to create and manipulate arrays with these data types:
```python
import numpy as np
# Creating a 1D array of strings
str_arr =  np.array(['a','bcd'])
print(str_arr)
print(str_arr.dtype)

arr = np.array(['a','bcd','efghijk'])
print(arr)
print(arr.dtype)

# Creating a 1D array of booleans
bool_arr = np.array([True, False, True])
print(bool_arr)
print(bool_arr.dtype)
```

Boolean arrays can be very useful for indexing and filtering data in Numpy. For example, a boolean array to select elements from another array that meet a certain condition.



**Short exercise**: Use boolean arrays to represent the state of qubits (e.g., True for |1⟩ and False for |0⟩) and perform operations based on their states.
```{admonition} Example here!
:class: dropdown
```python
import numpy as np

# Creating a 1D array of integers
int_arr = np.array([1, 2, 3, 4, 5])

# Creating a boolean array based on a condition
bool_arr = int_arr > 3
print(bool_arr)

# Using the boolean array to filter the integer array
filtered_arr = int_arr[bool_arr]

print("Original array:", int_arr)
print("Boolean array:", bool_arr)
print("Filtered array:", filtered_arr)
```

## 1.4 Linear algebra with Numpy
Numpy provides a comprehensive set of functions for performing linear algebra operations. 

### 1.4.1 Scalar Array/Matrix Operations

You can perform scalar operations on arrays and matrices, such as addition, subtraction, multiplication, and division. These operations are applied element-wise.


In [ ]:
import numpy as np
# Creating a 2D array (matrix)
A = np.array([[1,2],[3,4]], dtype='float')

# Displaying the original matrix
print(A, '')

# Performing scalar operations
print(2*A,'')

# Element-wise exponentiation
print(A**2,'')

# Element-wise division
print(A/2,'')

# Element-wise floor division
print(A//2,'')

# Element-wise addition
print(A+2,'')

# Element-wise subtraction
print(A-2,'')

# Element-wise modulus
print(A%2,'')



### 1.4.2 Array-Array Operations
As we have seen, you can perform element-wise operations between two arrays of the same shape.


In [ ]:
import numpy as np
# Creating two 2D arrays (matrices) of the same shape
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10], dtype='float')

print('arr1 + arr2 = ', arr1+arr2)
print('arr1 - arr2 = ', arr1-arr2)
print('arr1 * arr2 = ', arr1*arr2)
print('arr1 / arr2 = ', arr1/arr2)
print('arr1 ** arr2 = ', arr1**arr2)
print('arr1 // arr2 = ', arr1//arr2)
print('arr1 % arr2 = ', arr1%arr2)


While the above arrays are vectors we can perform the same operations higher-dimensional arrays (matrices) in the same way.


In [ ]:
import numpy as np
# Creating two 2D arrays (matrices) of the same shape
A = np.array([[1,2],[3,4]], dtype='float')
B = np.array([[5,6],[7,8]], dtype='float')

print('A + B = ', A + B)
print('A - B = ', A - B)
print('A * B = ', A * B)
print('A / B = ', A / B)
print('A ** B = ', A ** B)
print('A // B = ', A // B)
print('A % B = ', A % B)



**Short exercise**: Create two 3x3 matrices and perform element-wise addition, subtraction, multiplication, and division on them.

```{admonition} Example here!   
:class: dropdown
```python
import numpy as np

# Creating two 3x3 matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='float')
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]], dtype='float')

# Performing element-wise operations
addition = matrix1 + matrix2
subtraction = matrix1 - matrix2
multiplication = matrix1 * matrix2
division = matrix1 / matrix2    

print("Matrix 1:", matrix1)
print("Matrix 2:", matrix2)
print("Element-wise Addition:", addition)
print("Element-wise Subtraction:", subtraction)
print("Element-wise Multiplication:", multiplication)
print("Element-wise Division:", division)
```



### 1.4.3 Matrix Multiplication and Dot Product
For matrix multiplication, you can use the `@` operator or the `np.matmul()` function.


In [ ]:
import numpy as np
# Creating two 2D arrays (matrices)
A = np.array([[1,2],[3,4]], dtype='float')
B = np.array([[5,6],[7,8]], dtype='float')

# Performing matrix multiplication using the @ operator
C = A @ B
print('Matrix multiplication using @ operator:', C)

# Performing matrix multiplication using np.matmul()
D = np.matmul(A, B)
print('Matrix multiplication using np.matmul():', D)


You can also compute the dot product of two vectors using the `np.dot()` function or the `@` operator.


In [ ]:
import numpy as np
# Creating two 1D arrays (vectors)
vec1 = np.array([1, 2, 3], dtype='float')
vec2 = np.array([4, 5, 6], dtype='float')

# Computing the dot product using np.dot()
dot_product1 = np.dot(vec1, vec2)
print('Dot product using np.dot():', dot_product1)

# Computing the dot product using the @ operator
dot_product2 = vec1 @ vec2
print('Dot product using @ operator:', dot_product2)



**Short exercise**: Create two 2x2 matrices and compute their matrix product using both the `@` operator and the `np.matmul()` function. Then, create two 1D arrays (vectors) and compute their dot product using both the `np.dot()` function and the `@` operator.

```{admonition} Example here!   
:class: dropdown
```python
import numpy as np
# Creating two 2x2 matrices
matrix1 = np.array([[1, 2], [3, 4]], dtype='float)
matrix2 = np.array([[5, 6], [7, 8]], dtype='float)

# Computing matrix product using the @ operator
matrix_product1 = matrix1 @ matrix2

# Computing matrix product using np.matmul()
matrix_product2 = np.matmul(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix product using @ operator:\n", matrix_product1)
print("Matrix product using np.matmul():\n", matrix_product2)

# Creating two 1D arrays (vectors)
vector1 = np.array([1, 2, 3], dtype='float)
vector2 = np.array([4, 5, 6], dtype='float)

# Computing dot product using np.dot()
dot_product1 = np.dot(vector1, vector2)

# Computing dot product using the @ operator
dot_product2 = vector1 @ vector2
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Dot product using np.dot():", dot_product1)
print("Dot product using @ operator:", dot_product2)
```



### 1.4.4 Other Linear Algebra Operations
Numpy provides several other linear algebra operations, such as computing the transpose, inverse, determinant, and eigenvalues/eigenvectors of matrices.


In [ ]:
import numpy as np
# Creating a 2D array (matrix)
A = np.array([[1,2],[3,4]], dtype='float')

# Computing the transpose of the matrix
A_T = A.T
print('Transpose of A:', A_T)

# Computing the inverse of the matrix
A_inv = np.linalg.inv(A)
print('Inverse of A:', A_inv)

# Computing the determinant of the matrix
A_det = np.linalg.det(A)
print('Determinant of A:', A_det)

# Computing the eigenvalues and eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(A)
print('Eigenvalues of A:', eigenvalues)
print('Eigenvectors of A:', eigenvectors)



The conjugate transpose, also known as Hermitian transpose, of a matrix can be computed using the `.conj().T` method.


In [ ]:

import numpy as np
# Creating a 2D array (matrix) with complex numbers
A = np.array([[1+2j, 3+4j], [5+6j, 7+8j]], dtype='complex')

# Computing the conjugate transpose of the matrix
A_H = A.conj().T
print('Conjugate Transpose of A:', A_H)

Another example using complex numbers:

In [ ]:
import numpy as np
# Creating a 2D array (matrix) with complex numbers
A = np.array([[1+2j, 3+4j], [5+6j, 7+8j]], dtype='complex')

# Computing the conjugate transpose of the matrix
A_H = A.conj().T
print('Original Matrix A:\n', A)
print('Conjugate Transpose of A:\n', A_H)

# Verifying that the conjugate transpose is correct
print('A * A_H:\n', A @ A_H)


**Short exercise**: Create a 2x2 matrix and compute its transpose, inverse, determinant, and eigenvalues/eigenvectors.

```{admonition} Example here!   
:class: dropdown
```python
# Creating a 2x2 matrix
matrix = np.array([[2, 3], [1, 4]], dtype='float')

# Computing the transpose of the matrix
matrix_T = matrix.T

# Computing the inverse of the matrix
matrix_inv = np.linalg.inv(matrix)

# Computing the determinant of the matrix
matrix_det = np.linalg.det(matrix)

# Computing the eigenvalues and eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)   

print("Matrix:\n", matrix)
print("Transpose of the matrix:\n", matrix_T)
print("Inverse of the matrix:\n", matrix_inv)
print("Determinant of the matrix:\n", matrix_det)
print("Eigenvalues of the matrix:\n", eigenvalues)
print("Eigenvectors of the matrix:\n", eigenvectors)
```

## 1.5 Some useful Numpy tools
### 1.5.1 Random Number Generation
Numpy provides a module called `numpy.random` that contains functions for generating random numbers and performing random sampling. Some commonly used functions include:

| Function | Description | Example |
|----------|-------------|---------|
| `np.random.rand(d0, d1, ..., dn)` | Generates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1). | `random_array = np.random.rand(2, 3)` |
| `np.random.randn(d0, d1, ..., dn)` | Generates an array of the given shape and populates it with random samples from a standard normal distribution (mean 0, variance 1). | `random_array = np.random.randn(2, 3)` |
| `np.random.randint(low, high=None, size=None, dtype=int)` | Generates random integers from `low` (inclusive) to `high` (exclusive). | `random_integers = np.random.randint(0, 10, size=(2, 3))` |
| `np.random.choice(a, size=None, replace=True, p=None)` | Generates a random sample from a given 1D array. | `random_sample = np.random.choice([1, 2, 3, 4, 5], size=3)` |
| `np.random.normal(loc=0.0, scale=1.0, size=None)` | Generates random samples from a normal (Gaussian) distribution with specified mean (`loc`) and standard deviation (`scale`). | `random_samples = np.random.normal(loc=0, scale=1, size=100)` |


In [13]:
# examples of functions above
import numpy as np

# Example: Generating a random array using np.random.rand
random_array = np.random.rand(2, 3)
print("Random Array:\n", random_array)

# Example: Generating a random array using np.random.randn
random_array_normal = np.random.randn(2, 3)
print("Random Array from Standard Normal Distribution:\n", random_array_normal)

# Example: Generating random integers using np.random.randint
random_integers = np.random.randint(0, 10, size=(2, 3))
print("Random Integers:\n", random_integers)

# Example: Generating a random sample from a given 1D array using np.random.choice
random_sample = np.random.choice([1, 2, 3, 4, 5], size=3)
print("Random Sample from 1D Array:\n", random_sample)

# Example: Generating random samples from a normal distribution using np.random.normal
random_samples_normal = np.random.normal(loc=0, scale=1, size=100)
print("Random Samples from Normal Distribution:\n", random_samples_normal)

Random Array:
 [[0.37694305 0.65364276 0.20622774]
 [0.14076656 0.706544   0.09412629]]
Random Array from Standard Normal Distribution:
 [[ 1.67550762  0.44105564  0.85424859]
 [-0.86383158  0.60550915  0.05807451]]
Random Integers:
 [[6 8 8]
 [7 1 8]]
Random Sample from 1D Array:
 [4 2 3]
Random Samples from Normal Distribution:
 [-0.42460455  0.01946014 -0.08943071  1.63392247  1.05002629  1.08245712
 -1.47814715  1.49717868  0.26044638 -0.00242655  0.69456867 -1.98547462
 -1.84071043  0.32966679 -0.13356908  0.04744968 -0.26121088  0.60819926
  1.08271532 -1.27197607 -0.88771752  0.02345416 -0.87325354  0.14352347
  0.44193822  1.55751749 -0.27471463  0.08800555  0.07124709  0.98429144
 -0.88455541 -1.91291527 -2.39747015  0.14712158  1.6617236   1.00343181
 -1.07750628 -0.38665141 -0.38149357  0.54979728  0.164139   -0.57008778
  0.04975816 -2.03892747 -1.3300861   0.39509162 -1.57678649 -0.74820064
 -0.09240499  1.52201588 -1.52857098  1.28681863  0.40413775 -0.39314957
 -0.225740

## 1.6 Polynomial Fitting with Numpy
Numpy provides a convenient function `np.polyfit()` to fit a polynomial of a specified degree to a set of data points. The function takes in the x and y coordinates of the data points, the degree of the polynomial, and returns the coefficients of the fitted polynomial.

$$p(x,n) = c[0]x^n + c[2]x^{n-1} +...+ c[n-1]x ^1 + c[n]x^0 $$

where $c[i]$ is the i-th coefficient.

In Numpy we can perform many operations with polynomials.

Some useful polynomial functions in Numpy:

| Function | Description | Example |
|----------|-------------|---------|
| `np.polyfit(x, y, deg)` | Fits a polynomial of degree `deg` to the data points `(x, y)`. | `coefficients = np.polyfit(x, y, 2)` |
| `np.polyval(p, x)` | Evaluates a polynomial at specific values of `x`. | `y_fit = np.polyval(coefficients, x)` |
| `np.polyder(p, m=1)` | Computes the derivative of a polynomial. | `p_derivative = np.polyder(coefficients)` |
| `np.polyint(p, m=1, k=0)` | Computes the integral of a polynomial. | `p_integral = np.polyint(coefficients)` |
| `np.roots(p)` | Computes the roots of a polynomial. | `roots = np.roots(coefficients)` |


In [ ]:
import numpy as np
# Generating some sample data
x = np.linspace(-5, 5, 100)
y = 2*x**3 - 4*x**2 + 3*x + np.random.normal(0, 10, size=x.shape)

# Fitting a polynomial of degree 3 to the data
degree = 3
coefficients = np.polyfit(x, y, degree)

# Evaluating the fitted polynomial at the x values
y_fit = np.polyval(coefficients, x)

# Printing the coefficients of the fitted polynomial
print("Coefficients of the fitted polynomial:", coefficients)



**Short exercise**: Generate some sample data points that follow a quadratic relationship with some added noise. Fit a polynomial of degree 2 to the data and plot both the original data points and the fitted polynomial curve.

```{admonition} Example here!
:class: dropdown
```python
import numpy as np
import matplotlib.pyplot as plt 

# Generating some sample data
x = np.linspace(-10, 10, 100)
y = 3*x**2 + 2*x + 1 + np.random.normal(0, 20, size=x.shape)    

# Fitting a polynomial of degree 2 to the data
degree = 2
coefficients = np.polyfit(x, y, degree) 

# Evaluating the fitted polynomial at the x values
y_fit = np.polyval(coefficients, x)

# Printing the coefficients of the fitted polynomial
print("Coefficients of the fitted polynomial:", coefficients)

# Evaluating quality of the fit
residuals = y - y_fit
ss_res = np.sum(residuals**2)
ss_tot = np.sum((y - np.mean(y))**2)
r_squared = 1 - (ss_res / ss_tot)
print("R-squared value of the fit:\n", r_squared)

## Extra
# Plotting the original data points and the fitted polynomial curve
plt.scatter(x, y, label='Data Points', color='blue', alpha=0.5)
plt.plot(x, y_fit, label='Fitted Polynomial', color='red')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Polynomial Fitting with Numpy')
plt.legend()
plt.show()
```


## I/O Functions with Numpy

Numpy also offers a variety of functions for reading from and writing to files, which can be very useful for importing and exporting data. 

| Function | Description | Example |
|----------|-------------|---------|
| `np.loadtxt(fname, delimiter=',')` | Loads data from a text file. | `data = np.loadtxt('data.txt', delimiter=',')` |
| `np.savetxt(fname, X, delimiter=',')` | Saves an array to a text file. | `np.savetxt('data.txt', data, delimiter=',')` |
| `np.genfromtxt(fname, delimiter=',')` | Loads data from a text file, with more flexibility than `loadtxt`. | `data = np.genfromtxt('data.txt', delimiter=',')` |
| `np.save(file, arr)` | Saves an array to a binary file in `.npy` format. | `np.save('data.npy', data)` |
| `np.load(file)` | Loads an array from a binary file in `.npy` format. | `data = np.load('data.npy')` |
| `np.savez(file, *args, **kwds)` | Saves multiple arrays to a compressed `.npz` file. | `np.savez('data.npz', arr1=data1, arr2=data2)` |
| `np.load(file)` | Loads arrays from a compressed `.npz` file. | `data = np.load('data.npz')` |

There are lots of functionalities you can explore and use with NumPy I/O functions, for instance, you can define the format of the data when saving it to a text file using the `fmt` parameter in `np.savetxt`; also reading only specific columns or skipping headers when loading data using the `usecols` and `skip_header` parameters in `np.loadtxt` or `np.genfromtxt`.

The only limitation is that these functions are primarily designed for numerical data. If there is the case you have some non-numerical data, you will get an import error or unexpected behavior. In such cases, you might need to preprocess your data to remove non-numerical values or use alternative libraries like `pandas` which can handle mixed data types more gracefully.

If you need to read floating points with 'D' notation (common in Fortran, e.g. `1.23D+04`), you can use the `converters` parameter in `np.loadtxt` or `np.genfromtxt` to convert them to standard floating-point numbers as Python understands notation 'E' or 'e' (e.g. `1.23E+04`). 

```python
data = np.loadtxt('data.txt', delimiter=',', converters={0: lambda s: float(s.replace(b'D', b'e'))})
```